name: Rashid Meras Landing
theme: jekyll-theme-time-machine
title: Welcome to Rashid Meras homepage
description: Feel free to bookmark this to keep an eye on my project updates
url: "http://rashidmeras.github.io"
